stages:
  - build
  - test

build:
  #only: 
  #  - master
  stage: build
  image: node:14.9.0-alpine
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

test:
  only:
    - master
  allow_failure: true
  #hotfix for no tests present
  stage: test
  image: node:14.9.0-alpine
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test successfully!"